### ISSUE TITLE
[HyperNova] Add `Transcript` usage across the multifolding implementation

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/Nova#24]
We actually need a transcript which we can seed and grants us query capabilities in order to get randomness to commit to polynomials.

The suggestion is to use [merlin](https://crates.io/crates/merlin) but we can differ from it if needed.

**Comment by oskarth** [comment]
Can you elaborate on this? How is this different from the way it works with Spartan/Nova in Nova upstream?
